export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SUCCESS = "SUCCESS";
export const BEGIN = "BEGIN";
export const ERROR = "ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_uSER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";

export const CREATE_COMMENT_BEGIN = "CREATE_COMMENT_BEGIN";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR";

export const LIKE_POST_BEGIN = "LIKE_POST_BEGIN";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";

export const UPDATE_POST_BEGIN = "UPDATE_POST_BEGIN";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_ERROR = "UPDATE_POST_ERROR";

export const GET_POST_BEGIN = "GET_POST_BEGIN";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_ERROR = "GET_POST_ERROR";

export const GET_EXPLORE_BEGIN = "GET_EXPLORE_BEGIN";
export const GET_EXPLORE_SUCCESS = "GET_EXPLORE_SUCCESS";
export const GET_EXPLORE_ERROR = "GET_EXPLORE_ERROR";

export const ADD_JOB_BEGIN = "ADD_JOB_BEGIN";
export const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS";
export const ADD_JOB_ERROR = "ADD_JOB_ERROR";

export const SEARCH_SUCCESS = "SEARCH_SUCCESS";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const UPDATE_PROFILE_BEGIN = "UPDATE_PROFILE_BEGIN";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const REMOVE_FOLLOWER_SUCCESS = "REMOVE_FOLLOWER_SUCCESS";
export const ADD_FOLLOWER_SUCCESS = "ADD_FOLLOWER_SUCCESS";


export const UPDATE_JOB_BEGIN = "UPDATE_JOB_BEGIN";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";
export const UPDATE_JOB_ERROR = "UPDATE_JOB_ERROR";

export const CHANGE_VALUE_BEGIN = "CHANGE_VALUE_BEGIN";


export const SHOW_ALERT = "SHOW_ALERTS";
